/**
 * Agent configuration.
 * proxyPath must match keys in vite.config.js proxy.
 * healthPath uses Spring Boot Actuator.
 */
export const AGENTS = [
  {
    id:          'raw-agent',
    name:        'Raw Agent',
    description: 'Pure loop — no LangChain4j, no Spring AI, just HTTP',
    color:       '#EF4444',
    colorClass:  'bg-red-500',
    borderClass: 'border-red-500',
    textClass:   'text-red-400',
    proxyPath:   '/api/raw-agent',
    chatPath:    '/api/raw-agent/api/v1/agent/chat',
    healthPath:  '/api/raw-agent/actuator/health',
    chatField:   'message',
    icon:        'RAW',
  },
  {
    id:          'lc4j-agent-local',
    name:        'LangChain4j Agent Local',
    description: 'Raw loop + AiServices + local @Tool',
    color:       '#6366F1',
    colorClass:  'bg-indigo-500',
    borderClass: 'border-indigo-500',
    textClass:   'text-indigo-400',
    proxyPath:   '/api/lc4j-agent-local',
    chatPath:    '/api/lc4j-agent-local/api/v1/agent/aiservices',
    healthPath:  '/api/lc4j-agent-local/actuator/health',
    chatField:   'message',
    icon:        'LC4J',
  },
  {
    id:          'lc4j-agent-mcp',
    name:        'LangChain4j Agent MCP',
    description: 'Orchestrator + MCP Client (Java + Python)',
    color:       '#10B981',
    colorClass:  'bg-emerald-500',
    borderClass: 'border-emerald-500',
    textClass:   'text-emerald-400',
    proxyPath:   '/api/lc4j-agent-mcp',
    chatPath:    '/api/lc4j-agent-mcp/api/v1/mcp/chat',
    healthPath:  '/api/lc4j-agent-mcp/actuator/health',
    chatField:   'message',
    icon:        'MCP',
  },
  {
    id:          'spring-agent-local',
    name:        'Spring AI Agent Local',
    description: 'ChatClient + Advisors + local @Tool',
    color:       '#F59E0B',
    colorClass:  'bg-amber-500',
    borderClass: 'border-amber-500',
    textClass:   'text-amber-400',
    proxyPath:   '/api/spring-agent-local',
    chatPath:    '/api/spring-agent-local/api/v1/agent/chat',
    healthPath:  '/api/spring-agent-local/actuator/health',
    chatField:   'message',
    icon:        'SAI',
  },
  {
    id:          'spring-agent-mcp',
    name:        'Spring AI Agent MCP',
    description: 'ChatClient + MCP Client Orchestrator',
    color:       '#A855F7',
    colorClass:  'bg-purple-500',
    borderClass: 'border-purple-500',
    textClass:   'text-purple-400',
    proxyPath:   '/api/spring-agent-mcp',
    chatPath:    '/api/spring-agent-mcp/api/v1/mcp/chat',
    healthPath:  '/api/spring-agent-mcp/actuator/health',
    chatField:   'message',
    icon:        'MCP',
  },
]
